"use strict";var M=Object.create;var i=Object.defineProperty;var I=Object.getOwnPropertyDescriptor;var P=Object.getOwnPropertyNames;var R=Object.getPrototypeOf,$=Object.prototype.hasOwnProperty;var o=(e,r)=>()=>(r||e((r={exports:{}}).exports,r),r.exports),D=(e,r)=>{for(var n in r)i(e,n,{get:r[n],enumerable:!0})},f=(e,r,n,t)=>{if(r&&typeof r=="object"||typeof r=="function")for(let s of P(r))!$.call(e,s)&&s!==n&&i(e,s,{get:()=>r[s],enumerable:!(t=I(r,s))||t.enumerable});return e};var p=(e,r,n)=>(n=e!=null?M(R(e)):{},f(r||!e||!e.__esModule?i(n,"default",{value:e,enumerable:!0}):n,e)),k=e=>f(i({},"__esModule",{value:!0}),e);var h=o((K,l)=>{"use strict";l.exports=function(e){if(typeof e!="string")throw new Error("expected a string");return e.split(`
`).map(T).filter(Boolean)};function T(e,r){if(!e||!e.length||e.charAt(0)==="#")return null;var n=e.split(":");return{username:n[0],password:n[1],uid:n[2],gid:n[3],gecos:n[4],homedir:n[5],shell:n[6]}}});var v=o((_,m)=>{"use strict";var q=require("fs"),U=h();function C(){if(process.platform==="win32")return process.env.USERPROFILE?process.env.USERPROFILE:process.env.HOMEDRIVE&&process.env.HOMEPATH?process.env.HOMEDRIVE+process.env.HOMEPATH:process.env.HOME?process.env.HOME:null;if(process.env.HOME)return process.env.HOME;var e=N("/etc/passwd"),r=F(U(e),L());if(r)return r;var n=process.env.LOGNAME||process.env.USER||process.env.LNAME||process.env.USERNAME;return n?process.platform==="darwin"?"/Users/"+n:"/home/"+n:null}function F(e,r){for(var n=e.length,t=0;t<n;t++)if(+e[t].uid===r)return e[t].homedir}function L(){return typeof process.geteuid=="function"?process.geteuid():process.getuid()}function N(e){try{return q.readFileSync(e,"utf8")}catch{return""}}m.exports=C});var w=o((z,u)=>{"use strict";var g=require("os");typeof g.homedir<"u"?u.exports=g.homedir:u.exports=v()});var y=o((J,x)=>{var V=w(),E=require("path");x.exports=function(r){var n=V();return r.charCodeAt(0)===126?r.charCodeAt(1)===43?E.join(process.cwd(),r.slice(2)):n?E.join(n,r.slice(1)):r:r}});var B={};D(B,{default:()=>H});module.exports=k(B);var c=require("@raycast/api"),d=require("child_process");var b=p(require("fs")),A=require("child_process"),a=require("@raycast/api"),O=p(y());async function j(){let n=`${(0,a.getPreferenceValues)().androidSDK.replace("~",(0,O.default)("~"))}/platform-tools/adb`;if(b.existsSync(n))return n;throw new Error(`\u2757\uFE0FADB not found here: ${n}`)}async function S(){let e=await j(),r=(0,A.execSync)(`${e} devices`).toString().trim().split(`
`);if(r.length==1)throw new Error("\u2757No device seem to be connected.");return`${e} -s ${r[1].split("	")[0]}`}async function H(){let e;try{e=await S()}catch(t){await(0,c.showHUD)(`${t}`);return}let r=(0,d.execSync)(`${e} shell settings get global wifi_on`).toString().trim()==="1",n;r?(n="disable",await(0,c.showHUD)("\u{1F6DC} Turning off wifi")):(n="enable",await(0,c.showHUD)("\u{1F6DC} Turning on wifi")),(0,d.execSync)(`${e} shell svc wifi ${n}`)}
/*! Bundled license information:

expand-tilde/index.js:
  (*!
   * expand-tilde <https://github.com/jonschlinkert/expand-tilde>
   *
   * Copyright (c) 2015 Jon Schlinkert.
   * Licensed under the MIT license.
   *)
*/
