"use strict";var P=Object.create;var o=Object.defineProperty;var S=Object.getOwnPropertyDescriptor;var I=Object.getOwnPropertyNames;var R=Object.getPrototypeOf,D=Object.prototype.hasOwnProperty;var i=(e,r)=>()=>(r||e((r={exports:{}}).exports,r),r.exports),$=(e,r)=>{for(var t in r)o(e,t,{get:r[t],enumerable:!0})},a=(e,r,t,n)=>{if(r&&typeof r=="object"||typeof r=="function")for(let s of I(r))!D.call(e,s)&&s!==t&&o(e,s,{get:()=>r[s],enumerable:!(n=S(r,s))||n.enumerable});return e};var p=(e,r,t)=>(t=e!=null?P(R(e)):{},a(r||!e||!e.__esModule?o(t,"default",{value:e,enumerable:!0}):t,e)),k=e=>a(o({},"__esModule",{value:!0}),e);var h=i((G,f)=>{"use strict";f.exports=function(e){if(typeof e!="string")throw new Error("expected a string");return e.split(`
`).map(q).filter(Boolean)};function q(e,r){if(!e||!e.length||e.charAt(0)==="#")return null;var t=e.split(":");return{username:t[0],password:t[1],uid:t[2],gid:t[3],gecos:t[4],homedir:t[5],shell:t[6]}}});var l=i((K,m)=>{"use strict";var L=require("fs"),T=h();function U(){if(process.platform==="win32")return process.env.USERPROFILE?process.env.USERPROFILE:process.env.HOMEDRIVE&&process.env.HOMEPATH?process.env.HOMEDRIVE+process.env.HOMEPATH:process.env.HOME?process.env.HOME:null;if(process.env.HOME)return process.env.HOME;var e=N("/etc/passwd"),r=C(T(e),F());if(r)return r;var t=process.env.LOGNAME||process.env.USER||process.env.LNAME||process.env.USERNAME;return t?process.platform==="darwin"?"/Users/"+t:"/home/"+t:null}function C(e,r){for(var t=e.length,n=0;n<t;n++)if(+e[n].uid===r)return e[n].homedir}function F(){return typeof process.geteuid=="function"?process.geteuid():process.getuid()}function N(e){try{return L.readFileSync(e,"utf8")}catch{return""}}m.exports=U});var g=i((z,c)=>{"use strict";var v=require("os");typeof v.homedir<"u"?c.exports=v.homedir:c.exports=l()});var w=i((J,E)=>{var V=g(),x=require("path");E.exports=function(r){var t=V();return r.charCodeAt(0)===126?r.charCodeAt(1)===43?x.join(process.cwd(),r.slice(2)):t?x.join(t,r.slice(1)):r:r}});var j={};$(j,{default:()=>M});module.exports=k(j);var d=require("@raycast/api"),H=require("child_process");var A=p(require("fs")),y=require("child_process"),u=require("@raycast/api"),O=p(w());async function W(){let t=`${(0,u.getPreferenceValues)().androidSDK.replace("~",(0,O.default)("~"))}/platform-tools/adb`;if(A.existsSync(t))return t;throw new Error(`\u2757\uFE0FADB not found here: ${t}`)}async function b(){let e=await W(),r=(0,y.execSync)(`${e} devices`).toString().trim().split(`
`);if(r.length==1)throw new Error("\u2757No device seem to be connected.");return`${e} -s ${r[1].split("	")[0]}`}async function M(e){let r;try{r=await b()}catch(n){await(0,d.showHUD)(`${n}`);return}let t=e.arguments.text;await(0,d.showHUD)("\u270D\uFE0F Writing "+t),(0,H.execSync)(`${r} shell input text '${t}'`)}
/*! Bundled license information:

expand-tilde/index.js:
  (*!
   * expand-tilde <https://github.com/jonschlinkert/expand-tilde>
   *
   * Copyright (c) 2015 Jon Schlinkert.
   * Licensed under the MIT license.
   *)
*/
