"use strict";var M=Object.create;var o=Object.defineProperty;var R=Object.getOwnPropertyDescriptor;var b=Object.getOwnPropertyNames;var I=Object.getPrototypeOf,P=Object.prototype.hasOwnProperty;var i=(e,r)=>()=>(r||e((r={exports:{}}).exports,r),r.exports),k=(e,r)=>{for(var t in r)o(e,t,{get:r[t],enumerable:!0})},d=(e,r,t,n)=>{if(r&&typeof r=="object"||typeof r=="function")for(let s of b(r))!P.call(e,s)&&s!==t&&o(e,s,{get:()=>r[s],enumerable:!(n=R(r,s))||n.enumerable});return e};var p=(e,r,t)=>(t=e!=null?M(I(e)):{},d(r||!e||!e.__esModule?o(t,"default",{value:e,enumerable:!0}):t,e)),D=e=>d(o({},"__esModule",{value:!0}),e);var l=i((j,f)=>{"use strict";f.exports=function(e){if(typeof e!="string")throw new Error("expected a string");return e.split(`
`).map($).filter(Boolean)};function $(e,r){if(!e||!e.length||e.charAt(0)==="#")return null;var t=e.split(":");return{username:t[0],password:t[1],uid:t[2],gid:t[3],gecos:t[4],homedir:t[5],shell:t[6]}}});var m=i((G,h)=>{"use strict";var q=require("fs"),U=l();function C(){if(process.platform==="win32")return process.env.USERPROFILE?process.env.USERPROFILE:process.env.HOMEDRIVE&&process.env.HOMEPATH?process.env.HOMEDRIVE+process.env.HOMEPATH:process.env.HOME?process.env.HOME:null;if(process.env.HOME)return process.env.HOME;var e=L("/etc/passwd"),r=F(U(e),T());if(r)return r;var t=process.env.LOGNAME||process.env.USER||process.env.LNAME||process.env.USERNAME;return t?process.platform==="darwin"?"/Users/"+t:"/home/"+t:null}function F(e,r){for(var t=e.length,n=0;n<t;n++)if(+e[n].uid===r)return e[n].homedir}function T(){return typeof process.geteuid=="function"?process.geteuid():process.getuid()}function L(e){try{return q.readFileSync(e,"utf8")}catch{return""}}h.exports=C});var E=i((K,c)=>{"use strict";var v=require("os");typeof v.homedir<"u"?c.exports=v.homedir:c.exports=m()});var x=i((z,w)=>{var N=E(),g=require("path");w.exports=function(r){var t=N();return r.charCodeAt(0)===126?r.charCodeAt(1)===43?g.join(process.cwd(),r.slice(2)):t?g.join(t,r.slice(1)):r:r}});var B={};k(B,{default:()=>H});module.exports=D(B);var a=require("@raycast/api"),S=require("child_process");var y=p(require("fs"));var u=require("@raycast/api"),A=p(x());async function O(){let t=`${(0,u.getPreferenceValues)().androidSDK.replace("~",(0,A.default)("~"))}/platform-tools/adb`;if(y.existsSync(t))return t;throw new Error(`\u2757\uFE0FADB not found here: ${t}`)}async function H(){let e;try{e=await O()}catch(r){await(0,a.showHUD)(`${r}`);return}await(0,a.showHUD)("\u{1F501} Restarting ADB"),(0,S.execSync)(`${e} kill-server && ${e} start-server`)}
/*! Bundled license information:

expand-tilde/index.js:
  (*!
   * expand-tilde <https://github.com/jonschlinkert/expand-tilde>
   *
   * Copyright (c) 2015 Jon Schlinkert.
   * Licensed under the MIT license.
   *)
*/
