"use strict";var A=Object.create;var y=Object.defineProperty;var L=Object.getOwnPropertyDescriptor;var P=Object.getOwnPropertyNames;var k=Object.getPrototypeOf,R=Object.prototype.hasOwnProperty;var v=(n,i)=>{for(var t in i)y(n,t,{get:i[t],enumerable:!0})},$=(n,i,t,r)=>{if(i&&typeof i=="object"||typeof i=="function")for(let a of P(i))!R.call(n,a)&&a!==t&&y(n,a,{get:()=>i[a],enumerable:!(r=L(i,a))||r.enumerable});return n};var C=(n,i,t)=>(t=n!=null?A(k(n)):{},$(i||!n||!n.__esModule?y(t,"default",{value:n,enumerable:!0}):t,n)),T=n=>$(y({},"__esModule",{value:!0}),n);var _={};v(_,{default:()=>b});module.exports=T(_);var e=require("@raycast/api"),I=require("react"),p=C(require("fs")),g=C(require("path")),x=require("@raycast/api"),m=require("react/jsx-runtime");(0,e.launchCommand)({name:"menu",type:e.LaunchType.UserInitiated});var h=g.default.join(x.environment.supportPath,"remembering.csv"),D=!1;try{p.default.accessSync(h),D=!0}catch{console.log("File does not exist. Creating a new file...")}var S="";D&&(S=p.default.readFileSync(h,"utf-8"));var U=S.split(`
`),j=U.filter(n=>n.trim()!==""),B=j.join(`
`);p.default.writeFileSync(h,B);function E(){let n=new Date;try{let r=p.default.readFileSync(h,"utf8").trim().split(`
`).filter(u=>{let[s,l]=u.split(","),f="||&|",o=l.replace(f,",");return new Date(s)>n}),a=r.join(`
`)+`

`;return p.default.writeFileSync(h,a),r.map(u=>{let[s,l]=u.split(","),f="||&|",o=l.replace(f,",");return{expirationDate:new Date(s),content:o}})}catch{return[]}}function w(n,i){let t=new Date;return n.filter(r=>i.length===0?r.expirationDate>t:r.expirationDate>t&&r.content.toLowerCase().includes(i.toLowerCase()))}function V(n){let i=new Date,t=n.getTime()-i.getTime(),r=365*24*60*60*1e3,a=30*24*60*60*1e3,u=24*60*60*1e3,s=60*60*1e3,l=60*1e3,f=1e3;if(t>10*r)return"Forever";if(t<=0)return"Expired";if(t>=r){let o=Math.floor(t/r),d=t%r,c=Math.floor(d/a);return o===1?`Expires in ${o} year and ${c} months`:`Expires in ${o} years and ${c} months`}else if(t>=a){let o=Math.floor(t/a),d=t%a,c=Math.floor(d/u);return o===1?`Expires in ${o} month and ${c} days`:`Expires in ${o} months and ${c} days`}else if(t>=u){let o=Math.floor(t/u),d=t%u,c=Math.floor(d/s);return o===1?`Expires in ${o} day and ${c} hours`:`Expires in ${o} days and ${c} hours`}else if(t>=s){let o=Math.floor(t/s),d=t%s,c=Math.floor(d/l);return o===1?`Expires in ${o} hour and ${c} minutes`:`Expires in ${o} hours and ${c} minutes`}else if(t>=l){let o=Math.floor(t/l),d=t%l,c=Math.floor(d/f);return o===1?`Expires in ${o} minute and ${c} seconds`:`Expires in ${o} minutes and ${c} seconds`}else return`Expires in ${Math.floor(t/f)} seconds`}function b(){let[n,i]=(0,I.useState)(w(E(),"")),[t,r]=(0,I.useState)(""),a=s=>{let l=g.default.join(x.environment.supportPath,"remembering.csv"),o=p.default.readFileSync(l,"utf8").trim().split(`
`),d=o.splice(s,1)[0],c=o.join(`
`);p.default.writeFileSync(l,c);let M=n.filter((G,F)=>F!==s);i(M),(0,e.showToast)({title:"Deleted That Item!"}),(0,e.launchCommand)({name:"menu",type:e.LaunchType.UserInitiated})},u=s=>{r(s),i(w(E(),s))};return(0,e.launchCommand)({name:"menu",type:e.LaunchType.UserInitiated}),(0,m.jsx)(e.List,{searchBarPlaceholder:"Search remembered items",onSearchTextChange:u,children:n.length>0?n.map((s,l)=>(0,m.jsx)(e.ListItem,{title:s.content,subtitle:V(s.expirationDate),actions:(0,m.jsx)(e.ActionPanel,{children:(0,m.jsxs)(e.ActionPanel.Section,{children:[(0,m.jsx)(e.ActionPanel.Item,{title:"Add Item",icon:e.Icon.Document,onAction:()=>{(0,e.launchCommand)({name:"index",type:e.LaunchType.UserInitiated})},shortcut:{modifiers:["cmd"],key:"enter"}}),(0,m.jsx)(e.ActionPanel.Item,{title:"Copy Item",icon:e.Icon.CopyClipboard,onAction:()=>{e.Clipboard.copy(s.content),(0,e.showToast)({title:`Copied to "${s.content}" Clipboard!`})},shortcut:{modifiers:["cmd"],key:"."}}),(0,m.jsx)(e.ActionPanel.Item,{title:"Delete Item",icon:e.Icon.DeleteDocument,onAction:()=>{a(l)},shortcut:{modifiers:["cmd"],key:"backspace"}})]})})},l)):(0,m.jsx)(e.List.EmptyView,{icon:{source:e.Icon.Stars},title:"Woohoo! You got nothing to do!",description:"Click \u23CE to remember something!",actions:(0,m.jsx)(e.ActionPanel,{children:(0,m.jsx)(e.ActionPanel.Item,{title:"Add Item",icon:e.Icon.Plus,onAction:()=>{(0,e.launchCommand)({name:"index",type:e.LaunchType.UserInitiated})},shortcut:{modifiers:["cmd"],key:"enter"}})})})})}
